### ISSUE TITLE
Need to fix two changes to run game

### ISSUE THREAD

**Issue by DhruvAerosol** [shammadahmed/tic-tac-toe-game#2]
1) Need to remove lines generated due to merge in grid.vue file.
(https://github.com/shammadahmed/tic-tac-toe-game/blob/master/src/components/Grid.vue#L120-L123)
2) package.json - parsing error due to extra "," near line 9.
(https://github.com/shammadahmed/tic-tac-toe-game/blob/master/package.json#L9)

**Comment by shammadahmed** [comment]
Thanks @DhruvAerosol, I've merged both PRs.
